org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = fi.dy.masa
mod_id = tweakeroo
mod_name = Tweakeroo
author = masa
mod_file_name = tweakeroo-fabric

# Current mod version
mod_version = 0.23.999-dev

# Required malilib version
malilib_version = aca143d835

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 25w03a
minecraft_version = 25w03a
mappings_version = 25w03a+build.3

fabric_loader_version = 0.16.10
mod_menu_version = 13.0.0
# fabric_api_version = 0.114.4+1.21.5
