org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = fi.dy.masa
mod_id = tweakeroo
mod_name = Tweakeroo
author = masa
mod_file_name = tweakeroo-fabric

# Current mod version
mod_version = 0.26.99-dev

# Required malilib version
malilib_version = 41bf2732a3

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 25w46a
minecraft_version = 25w46a
mappings_version = 25w46a+build.3

fabric_loader_version = 0.17.3
mod_menu_version = 16.0.0-rc.1
# fabric_api_version = 0.138.4+1.21.11
