org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = fi.dy.masa
mod_id = tweakeroo
mod_name = Tweakeroo
author = masa
mod_file_name = tweakeroo-fabric

# Current mod version
mod_version = 0.28.5-sakura.2

# Required malilib version
malilib_version = 0.28.6-sakura.1

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 26.1.2
minecraft_version = 26.1.2

fabric_loader_version = 0.19.2
mod_menu_version = 18.0.0-beta.1
fabric_api_version = 0.149.1+26.1.2

conditionalmixin_version = 0.6.4
